/**
 * Control class for the 'createLoginAccount' admin use case.
 * @author Ben Donkin
 *
 */
public class createLoginAccountControl {
	
	private DataManager dataManager;

	
	public createLoginAccountControl() {
		dataManager = MainMenu.getDataManager();
	}
	
	/**
	 * 
	 * @param acc
	 * @param type
	 * @return the accountId that was automatically generated by mysql
	 */
	public int createAccount(Account acc) {
		return dataManager.handleCreateAccount(acc, acc.getAccountType());
	}
	
	public void createStudent(StudentAccount studAcc) {
		dataManager.handleCreateStudent(studAcc);
	}

	
	public void createTA(TA_Account TA_Acc) {
		dataManager.handleCreateTA(TA_Acc);
	}

	
	public void createProf(ProfessorAccount profAc) {
		dataManager.handleCreateProf(profAc);
	}

	
	public void createAdmin(AdminAccount adminAc) {
		dataManager.handleCreateAdmin(adminAc);
	}
}
